### ISSUE TITLE
ColorRef can't be used as a Color in Flutter 3.27.0.

### ISSUE THREAD

**Issue by mhorn00** [marcglasberg/themed#12]
After upgrading to Flutter 3.27.0, all instances of ColorRef will not resolve to the actual Color it represents.
This forces me to use the 'color' property on the ColorRef instance for the real color, which is not const.

```
Container(color: MyTheme.primary); // This container will act like it was passed null for color

Container(color: MyTheme.primary.color); // This gets the color correctly, but the value is no longer const
``` 

The Flutter team is intending on marking the Color class as sealed, and it seems like that will affect the functionality of this package.

**Comment by marcglasberg** [comment]
I'll have a look into that issue.

**Comment by marcglasberg** [comment]
@mhorn00 Version 8.0.0 is compatible with Flutter 3.27.0 and up:

  ```yaml
  dependencies:
    themed: ^8.0.0
  ``` 

However, you said the Flutter team is intending on marking the Color class as sealed. How do you know about this? Could you please give me as much information as you can about this, so that maybe I can talk to them and ask them not to do it?

**Comment by mhorn00** [comment]
Thanks for the fix, I'll be able to try it out soon.

In the breaking changes and migrations notes of the 3.27.0 release, they detail many changes to the Color class in the "[Color wide gamut support](https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework)" section. The relevant change is mentioned in a note under the "Implementors of Color" header.

**Comment by marcglasberg** [comment]
@mhorn00 I’ve opened a Flutter issue, asking them not to seal the Color class. If you agree, please consider upvoting it here: https://github.com/flutter/flutter/issues/160613
