### ISSUE TITLE
firstPage não. Mas, secondPage sim.

### ISSUE THREAD

**Issue by catalunha** [marcglasberg/themed#2]
Olá Marcelo,
Parabens mais uma vez pela sua fantástica contribuição no desenvolvimento deste package, Themed. 
Desde que conheci seu trabalho com o async_redux, o qual utilizo muito, mais admiro seu trabalho e desejo seu sucesso e crescimento pessoal e profissional. Deus sabe o quanto tenho orado por vc e sua familia.
Mas vamos a minha duvida, talvez uma issue. Decida por favor.
Considere estes temas do seu exemplo:
```
MyTheme
  static const primary = ColorRef(Colors.orange);
  static const onPrimary = ColorRef(Colors.black);
anotherTheme
Map<ThemeRef, Object> anotherTheme = {
  MyTheme.primary: Colors.grey,
  MyTheme.onPrimary: Colors.yellow,
```
No exemplo deste package acrescentei apenas este código para alterar a cor do appBar e ele tem executado corretamente a mudança da cor (a cor do background da appBar muda alternadamente com a cor de seu texto):
```dart
 appBarTheme: const AppBarTheme(
            backgroundColor: MyTheme.primary,
            foregroundColor: MyTheme.onPrimary,
          ),
```
Aplicando este mesmo código a meu projeto ele NÃO tem mudado a cor do texto da appBar alternadamente com o background na appBar, na HomePage de onde parte o click no action para mudar a cor, MAS corretamente nas demais telas.
Este é o código do meu main.dart.
```dart
    return StoreProvider<AppState>(
      store: store,
      child: Themed(
        defaultTheme: myThemeOrange,
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          scrollBehavior: MyCustomScrollBehavior(),
          title: 'ClassFrase',
          navigatorKey: navigatorKey,
          routes: Routes.routes,
          initialRoute: '/',
          theme: ThemeData(
            primaryColor: MyTheme.primary,
            appBarTheme: const AppBarTheme(
              backgroundColor: MyTheme.primary,
              foregroundColor: MyTheme.onPrimary,
            ),
           ...
```
O fluxo do initialRoute segue: SplashConnector -> HomePageConnector -> HomePage. Onde contem o botão no action para mudança de cor. A HomePage muda apenas o background e nao a cor do texto. Mas a SecondPage sim muda conforme seu exemplo.

Você tem alguma sugestão com tão pouca informação que eu dei ? Pois os demais passos são iguais aos que vc orienta no exemplo.

**Comment by marcglasberg** [comment]
Ok, tem como me passar um arquivo único, completo com método main e tudo, para que eu possa simplesmente rodar e ver o problema?

**Comment by catalunha** [comment]
Grato pela pronta atenção.
Reproduzi a situação que enfrento usando este projeto exemplo: https://github.com/catalunha/test_themed
E ele reproduz exatamente o que acontece em meu projeto real.
Se você executar o projeto com este código:
```dart
        home: const HomePage(),
```
Verá que ele atualiza o theme perfeitamente. Veja as imagens:
![Screenshot_1636114804](https://user-images.githubusercontent.com/19995819/140509302-0156bfc9-0b4e-401d-b575-be9fe3b7336d.png)
![Screenshot_1636114809](https://user-images.githubusercontent.com/19995819/140509318-06e09f62-bd09-44d9-b83a-5c4a17a85033.png)
Mas se usarmos o conceito de routes. Com este código:
```dart
        navigatorKey: navigatorKey,
        routes: Routes.routes,
        initialRoute: '/',
```
Ele passa a não atualizar o theme da pagina home, mas da secondPage sim. E observe também que um dos botões muda, o outro não. Veja as imagens:
![Screenshot_1636114960](https://user-images.githubusercontent.com/19995819/140509587-f1913f2a-db27-4d6e-9423-8362edb29bdf.png)
![Screenshot_1636114969](https://user-images.githubusercontent.com/19995819/140509597-d6858f0e-129c-4ce5-849b-47742a30f99d.png)
![Screenshot_1636114983](https://user-images.githubusercontent.com/19995819/140509624-b6f69618-d1d8-46c5-afb4-f0a3edcf2656.png)

**Comment by marcglasberg** [comment]
Pelo que consegui analisar, a questão toda é que o `Themed` está mudando o valor de variáveis constantes, no caso o `ThemeData`, mas o Flutter percebe que o `ThemeData` é o mesmo e não avisa todos os widgets que dependem do `Theme`. 

Eu estou forcando o rebuild de todos os widgets, mas o Flutter está "otimizando" a renderização do texto do botão, evitando que ele seja redesenhado. Ou seja, ele acha que o texto nao mudou, entao ele nao redesenha, mesmo com o rebuild.

Note que se vc mudar o texto do botao ele redesenha. Por exemplo, se o seu texto do botão fosse algo como `Text('Go to first page. ${ThemeApp.primary}')` entao ele detectaria que o botao mudou, e acabaria alterando a cor também. Isso prova que o botao está sim sendo rebuildado. 

Infelizmente, embora eu nao ache impossivel que exista uma solucao, eu nao tenho tempo no momento para fazer um deep dive. Idealmente eu deveria fazer o `Theme` perceber que o `ThemeData` mudou. Por outro lado talvez não exista um solução e isso seja uma limitação insoluvel do pacote. 

Uma solução ruim para isso, mas que resolveria, seria você forçar o widget Themed (ou o MaterialApp) a reiniciar completamente a árvore de widgets. Basta atribuir uma key, e daí alterar essa key logo depois de mudar o Theme. Entretanto, isso vai fazer initState em todos os StatefulWidgets do aplicativo, o que pode ser algo viável ou não, dependendo do aplicativo.

Peço desculpas por não ter uma solução.
