### ISSUE TITLE
Themed aplicado ao brightness

### ISSUE THREAD

**Issue by catalunha** [marcglasberg/themed#3]
Olá Marcelo, 
Parabens mais uma vez pela sua fantástica contribuição no desenvolvimento deste package, Themed.  
Desde que conheci seu trabalho com o async_redux, o qual utilizo muito, mais admiro sua genealidade em programar e desejo seu sucesso e crescimento pessoal e profissional. 
Deus sabe o quanto tenho orado por vc e sua familia.
Mas vamos a minha duvida, talvez uma issue. Decida por favor.

Mudanças de parametros como brightness para dark / light e MaterialColor no primarySwatch não podem ser utilizados no Themed. Assim eu poderia usar uma base ja estabelecida e mudar apenas algumas cores no theme:... 

Para uma mudança mais simples como esta entre dark / light eu deveria seguir que abordagem ? 
Seria reconstruir o ColorScheme completo para cada tipo deste ? Mas ele também requer o brightness.

Eu deveria mudar a cor de cada widget como vc fez com o elevatedButtonTheme aplicando assim mudanças especificas para  appBarTheme, buttonTheme, floatingActionButtonTheme, etc ?

**Comment by marcglasberg** [comment]
De fato, o Themed no momento permite apenas mudar cor (através do ColorRef) e estilo de texto (através de TextStyleRef). Para mudar outras classes eu teria que inclui-las no Themed. Eu não fiz isso, pois nos meus aplicativos eu nunca precisei alterar mais do que essas duas classes. Se no futuro eu precisar, poderei expandir o Themed para ter mais classes também.

Mas de fato, tem toda razão, está faltando. Infelizmente no momento não tenho como incluir mais classes. Se você precisa de algo mais completo no momento talvez tenha que fazer de outra forma, ou então o pacote no momento não lhe atenda e seja preciso não usá-lo.
