### ISSUE TITLE
duplicate keys issue

### ISSUE THREAD

**Issue by inteist** [marcglasberg/themed#8]
getting a duplicate key issue with the following code:

Map<ThemeRef, Object> blue = {
  ThemeStyle.primaryColor: Colors.blue,
  ThemeStyle.colorAccent: Colors.blueAccent,
};

it seems that the ColorRef needs a proper implementation of the equality and hashcode methods?

something like:

```dart 
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorRef && runtimeType == other.runtimeType && color == other.color;

  @override
  int get hashCode => color.hashCode;
```

I am farily new to all this. Maybe it's something really silly that I am missing?

**Comment by inteist** [comment]
oh, I got it. I had the default colors all set to the same colors - it all makes sense... Sorry... Like I said - very new to dart/flutter.

**Comment by marcglasberg** [comment]
You can indeed have more than one color key set to the same color, but then you should define an id string, just to diferentiate them as different constants. For example:

```dart
class MyTheme {
  static const colorA = ColorRef(Colors.white, id:'A');
  static const colorB = ColorRef(Colors.white, id:'B');
  static const colorB = ColorRef(colorA, id:'C');
}
```
